---
- name: Backup Let's Encrypt cert and copy to local machine
  hosts: ec2
  become: true
  vars_files:
    - group_vars/ec2.yml
  tasks:

    - name: Ensure zip and awscli are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: [zip, awscli]

    - name: Zip Self-signed public cert
      ansible.builtin.command: >
        tar -czvf {{ self_signed_cert_zip }} {{ self_signed_public_cert }}
      args:
        creates: "{{ self_signed_cert_zip }}"

    - name: Upload cert backup to S3
      ansible.builtin.command: >
        aws s3 cp {{ self_signed_cert_zip }} s3://{{ s3_bucket_name }}/{{ s3_cert_key }}

    - name: Zip Selfsigned private key
      ansible.builtin.command: >
        tar -czvf {{ self_signed_private_key_zip }} {{ self_signed_private_key }}
      args:
        creates: "{{ self_signed_private_key_zip }}"

    - name: Upload cert backup to S3
      ansible.builtin.command: >
        aws s3 cp {{ self_signed_private_key_zip }} s3://{{ s3_bucket_name }}/{{ s3_private_key }}