---
- name: Create a virtual environment for Certbot and upgrade pip
  hosts: all
  become: yes
  gather_facts: yes

  # vars:
  #   venv_path: "/opt/certbot"
  vars_files:
    - ../group_vars/global_vars.yml # Ensure this file contains the necessary variables

  tasks:

    - name: Ensure python3 and python3-pip are installed
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present

    # - name: Ensure python3-venv is installed
    #   ansible.builtin.package:
    #     name: python3-venv
    #     state: present

    - name: Create virtual environment at {{ venv_path }}
      ansible.builtin.command:
        cmd: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}/bin/activate"

    - name: Upgrade pip inside the virtual environment
      ansible.builtin.command:
        cmd: "{{ venv_path }}/bin/pip install --upgrade pip"

    - name: Activate virtual environment
      ansible.builtin.shell: |
        source {{ venv_path }}/bin/activate
      args:
        executable: /bin/bash