---
- name: Install Certbot and dependencies
  hosts: web
  become: true
  gather_facts: true

  vars:
    certbot_packages:
      - python3
      - python3-pip
      - python3-devel
      - augeas-devel
      - gcc

  vars_files:
    - ../group_vars/global_vars.yml # Ensure this file contains the necessary variables

  tasks:

    - name: Remove any existing Certbot installed via dnf
      ansible.builtin.dnf:
        name: certbot
        state: absent
        
    - name: Ensure required packages are installed
      ansible.builtin.dnf:
        name: "{{ certbot_packages }}"
        state: present
        update_cache: true

    - name: Install Certbot using pip
      ansible.builtin.command: "{{ venv_path }}/bin/pip install certbot certbot-nginx"
      # ansible.builtin.pip:
      #   name: certbot
      #   executable: pip3
      #   state: present

    - name: Verify Certbot installation
      ansible.builtin.shell: "source {{ venv_path }}/bin/activate && certbot --version"
      register: certbot_version

    - name: Show Certbot version
      ansible.builtin.debug:
        msg: "Installed Certbot version: {{ certbot_version.stdout }}"
