---
- name: Upload local SSL certificate to S3
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/localhost.yml

  tasks:

    - name: Check if certificate directory exists
      ansible.builtin.stat:
        path: "{{ local_cert_path }}/{{ domain_name }}"
      register: cert_dir

    - name: Fail if certificate not found
      ansible.builtin.fail:
        msg: "Certificate not found for domain {{ domain_name }}."
      when: not cert_dir.stat.exists

    - name: Create zip archive of Let's Encrypt directory
      ansible.builtin.command: >
        tar -czvf {{ s3_cert_zip }} {{ local_cert_path }}
      args:
        creates: "{{ s3_cert_zip }}"

    - name: Upload zip archive to S3
      ansible.builtin.command: >
        aws s3 cp {{ s3_cert_zip }} s3://{{ s3_bucket_name }}/{{ s3_key }}
      register: s3_upload

    - name: Show upload result
      ansible.builtin.debug:
        msg: "{{ s3_upload.stdout }}"
