---
- name: Install and configure NGINX on EC2 host
  hosts: web
  become: yes
  gather_facts: no
  connection: ssh

  tasks:
    - name: Update package index (Amazon Linux / RHEL-based)
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install NGINX
      shell: sudo yum install -y nginx

      register: nginx_install_result
      # ansible.builtin.yum:
      #   name: nginx
      #   state: present

    - name: Enable and start NGINX
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started

    - name: Allow HTTP and HTTPS in firewalld (if firewalld is used)
      ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      loop:
        - http
        - https
      when: ansible_facts.services['firewalld.service'] is defined

    - name: Ensure NGINX is reachable on port 80
      ansible.builtin.wait_for:
        port: 80
        state: started
        delay: 5
        timeout: 30

    - name: Display NGINX status
      ansible.builtin.command: systemctl status nginx
      register: nginx_status
      changed_when: false

    - name: Print NGINX status
      ansible.builtin.debug:
        var: nginx_status.stdout_lines
