---
- name: Deploy Secure NGINX Configuration
  hosts: web
  become: yes

  tasks:

    - name: Ensure app folder exists
      file:
        path: /home/ec2-user/app/
        state: directory
        mode: 0777
        owner: ec2-user
        group: ec2-user
      become: yes

    - name: Remove webapp.conf directory if it exists
      ansible.builtin.file:
        path: /home/ec2-user/app/webapp.conf
        state: absent
      when: webapp_conf_stat.stat.isdir is defined and webapp_conf_stat.stat.isdir

    - name: Stat webapp.conf to check if it's a directory
      ansible.builtin.stat:
        path: /home/ec2-user/app/webapp.conf
      register: webapp_conf_stat

    - name: Deploy webapp HTTPS reverse proxy configuration
      ansible.builtin.template:
        src: ../templates/webapp.conf.j2 # Path to your local static conf file
        dest: /home/ec2-user/app/webapp.conf
        owner: root
        group: root
        mode: '0644'

    # - name: Check if the original nginx.conf file exists
    #   ansible.builtin.stat:
    #     path: /etc/nginx/nginx.conf
    #   register: nginx_conf_stat # Save the result into a variable

    # - name: Rename nginx.conf to nginx.conf.bak if it exists
    #   ansible.builtin.command:
    #     cmd: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
      
    #   # This task will only run if the 'stat' task found the file.
    #   when: nginx_conf_stat.stat.exists

    # - name: Deploy custom nginx.conf
    #   ansible.builtin.template:
    #     src: ../templates/nginx.conf.j2 # Path to your local static conf file
    #     dest: /etc/nginx/nginx.conf
    #     owner: root
    #     group: root
    #     mode: '0644'
    #   notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded